#!/bin/bash

# Rotate root's mail file to prevent it from growing too large
# Save rotated files

# ....................................
### define varibles
# ....................................
SetDefaults () {
   # location of saved  files
   LOGDIR=/tank/root/logs/var/

   # root's mail file
   MAILFILE=/var/spool/mail/root
   LMMAILFILE=/var/spool/mail/lmwriter

   # saved mail file name with timestamp
   DATE=`date +%Y-%m-%d`
   OLD_MAILFILE=$LOGDIR/mail/root-mail-$DATE
   OLD_LMMAILFILE=$LOGDIR/mail/lmwriter-mail-$DATE

   if [ ! -d $LOGDIR/mail ] ; then
      mkdir -p $LOGDIR/mail
   fi
   
   if [ ! -d $LOGDIR/pgbouncer ] ; then
      mkdir -p $LOGDIR/pgbouncer
   fi
}


# ....................................
### save mail files
# ....................................
SaveMail () {
   # save current mail file
   if [ -f $MAILFILE ] ; then
      mv $MAILFILE $OLD_MAILFILE
      gzip $OLD_MAILFILE
   fi

   if [ -f $LMMAILEFILE ] ; then
      mv $LMMAILFILE $OLD_LMMAILFILE
      gzip $OLD_LMMAILFILE
   fi
}

